from __future__ import annotations

import argparse
from pathlib import Path

from libgguf.libgguf_numpy.libgguf_numpy import _get_iq3_s_lookup, _get_iq3_xxs_lookup


ROOT = Path(__file__).resolve().parents[1]
HEADER_PATH = ROOT / "src/libgguf/libgguf_cuda/csrc/libgguf_cuda_iq3_neighbours.cuh"
BANNER = """// This file is generated by scripts/generate_cuda_iq3_neighbours.py; do not edit by hand.
// Regenerate with: python scripts/generate_cuda_iq3_neighbours.py

"""


def _format_array(values: list[int], *, suffix: str = "", per_line: int = 16) -> str:
    lines: list[str] = []
    for i in range(0, len(values), per_line):
        chunk = values[i : i + per_line]
        lines.append("    " + ", ".join(f"{value}{suffix}" for value in chunk))
    return ",\n".join(lines)


def _emit(name: str, lookup: tuple) -> str:
    kmap, neighbours, _ = lookup
    offsets = [0]
    flat: list[int] = []
    for key in range(8**4):
        if kmap[key] >= 0:
            offsets.append(len(flat))
            continue
        values = [int(value) for value in neighbours[key]]
        flat.extend(values)
        offsets.append(len(flat))

    return f"""static const __device__ uint32_t {name}_neighbour_offsets[IQ3_GRID_LOOKUP_SIZE + 1] = {{
{_format_array(offsets, suffix="u", per_line=12)}
}};

static const __device__ uint16_t {name}_neighbours[{len(flat)}] = {{
{_format_array(flat, suffix="u", per_line=16)}
}};
"""


def generate_header() -> str:
    output = BANNER
    output += "#pragma once\n\n"
    output += _emit("iq3xxs", _get_iq3_xxs_lookup())
    output += "\n"
    output += _emit("iq3xs", _get_iq3_s_lookup())
    return output


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate or check the CUDA IQ3 neighbor header.")
    parser.add_argument("--check", action="store_true", help="Fail if the tracked header is out of date")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    output = generate_header()
    if args.check:
        if HEADER_PATH.read_text(encoding="utf-8") != output:
            raise SystemExit(
                "src/libgguf/libgguf_cuda/csrc/libgguf_cuda_iq3_neighbours.cuh is out of date; "
                "run scripts/generate_cuda_iq3_neighbours.py"
            )
        return
    HEADER_PATH.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
