from __future__ import annotations

NATIVE_SOURCES = [
    "csrc/libgguf.cpp",
    "csrc/common/libgguf_common.cpp",
    "csrc/common/libgguf_tables.cpp",
    "csrc/common/libgguf_iq_tables.cpp",
    "csrc/common/libgguf_cpu.cpp",
    "csrc/common/libgguf_validate.cpp",
    "csrc/quant/quant_q1_0.cpp",
    "csrc/quant/quant_q4_0.cpp",
    "csrc/quant/quant_q4_0_sse2.cpp",
    "csrc/quant/quant_q4_0_avx2.cpp",
    "csrc/quant/quant_q4_1.cpp",
    "csrc/quant/quant_q5_0.cpp",
    "csrc/quant/quant_q5_1.cpp",
    "csrc/quant/quant_q8_0.cpp",
    "csrc/quant/quant_q8_0_sse2.cpp",
    "csrc/quant/quant_q8_0_avx2.cpp",
    "csrc/quant/quant_q2_k.cpp",
    "csrc/quant/quant_q3_k.cpp",
    "csrc/quant/quant_q4_k.cpp",
    "csrc/quant/quant_q5_k.cpp",
    "csrc/quant/quant_q6_k.cpp",
    "csrc/quant/quant_iq1_s.cpp",
    "csrc/quant/quant_iq1_m.cpp",
    "csrc/quant/quant_iq2_xxs.cpp",
    "csrc/quant/quant_iq2_xs.cpp",
    "csrc/quant/quant_iq2_s.cpp",
    "csrc/quant/quant_iq3_xxs.cpp",
    "csrc/quant/quant_iq3_s.cpp",
    "csrc/quant/quant_iq4_nl.cpp",
    "csrc/quant/quant_iq4_xs.cpp",
    "csrc/quant/quant_tq1_0.cpp",
    "csrc/quant/quant_tq2_0.cpp",
    "csrc/quant/quant_mxfp4.cpp",
    "csrc/quant/quant_nvfp4.cpp",
]
